### ISSUE TITLE
vault template read templates from command line

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/vault-cli#123]
If we can make it easier to provide the template in the command line, that might make it really easy to do tasks like "write a given secret on a file on the disk".

Use case might be "writing nginx certificate at the start of the process in systemd's `PreExecStart`"

**Comment by ewjoachim** [comment]
(ping @mgu )

**Comment by mgu** [comment]
to you want to improve the `template` command of just add a `--output` option to `get` ?

**Comment by ewjoachim** [comment]
both work

**Comment by ewjoachim** [comment]
We added -o to get.
