### ISSUE TITLE
Is that possible to add read command to CLI to read single secret from my secret path?

### ISSUE THREAD

**Issue by sravankurra** [peopledoc/vault-cli#136]
Write to read single secret from my secret PATH the cli client is not support it 
###Version
vault -V
vault-cli 0.13.0
License: Apache Software License

$ vault read secret/my-secret
Key                 Value
---                 -----
refresh_interval    768h
foo                 bar

### Expecting command 
vault read  -field=foo  secret/my-secret

**Comment by ewjoachim** [comment]
If I understand you question correctly, it's one of the new features of 1.x.x :) 

```console
$ vault set secret/my-secret key=value
Done
$ vault get secret/my-secret key
value
```

Does this answer your question ?

**Comment by ewjoachim** [comment]
Feel free to reopen if needed :)

**Comment by sravankurra** [comment]
@ewjoachim Thank you it's working from version 1.3.1
