### ISSUE TITLE
vault-cli set-all

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/vault-cli#187]
Load multiple keys at once from a format compatible with (flat) get-all.

This can be useful to move secrets between two vault clusters:
```console
$ vault --config-file=a.yml get-all | vault --config-file=b.yml set-all
```

I'm guessing there would be a single optional positional argument for the file which defaults to `-`, interpreted as `stdin`.
Yaml content should be checked for format: it should be a valid yaml, containing an object with string keys and each value is itself an object.
We should then defer individual writes to `set_value` and provide the same set of flags to handle safe/unsafe overwriting.

**Comment by johnyalejandro001** [comment]
Hello Ewjoachim,

The current solution that I'm working is way more simpler(more like a script that the actual client tool that you wrote) 

import os
import hvac
import base64
from pprint import pprint

def print_to_stdout(*a):
    os.system("echo {0}".format(*a))

## Grab Vault endpoint and main root path from an environment variable
vault_url_source = os.environ.get('VAULT_URL_SOURCE')
vault_root_path = os.environ.get('VAULT_ROOT_PATH')
## Grabs all the environment variables from base64 enconded and decoded them
auth_chain_cert_source_encoded = os.environ.get('VAULT_CHAIN_CERT_SOURCE')
auth_public_cert_source_encoded = os.environ.get('VAULT_PUBLIC_CERT_SOURCE')
auth_private_key_source_encoded = os.environ.get('VAULT_PRIVATE_KEY_SOURCE')
auth_chain_cert_source_decode = base64.b64decode(auth_chain_cert_source_encoded)
auth_public_cert_source_decode = base64.b64decode(auth_public_cert_source_encoded)
auth_private_key_source_decode = base64.b64decode(auth_private_key_source_encoded)
#auth_chain_cert_destination_encoded = os.environ.get('VAULT_CHAIN_CERT_DESTINATION')
#auth_public_cert_destination_encoded = os.environ.get('VAULT_PUBLIC_CERT_DESTINATION')
#auth_private_key_destination_encoded = os.environ.get('VAULT_PRIVATE_KEY_DESTINATION')
#auth_chain_cert_destination_decode = base64.b64decode(auth_chain_cert_destination_encoded)
#auth_public_cert_destination_decode = base64.b64decode(auth_public_cert_destination_encoded)
#auth_private_key_destination_decode = base64.b64decode(auth_private_key_destination_encoded)
auth_public_cert_source_path = '/tmp/auth_public_cert.pem'
auth_private_key_source_path = '/tmp/auth_private_key.pem'
auth_chain_cert_source_path = '/tmp/auth_chain_cert.pem'

#Function check if all the requires certs are in the tmp location if not will write them from the decode environment variable
def generate_certs():
    try:
        if os.path.exists(auth_public_cert_source_path):
            print_to_stdout("Chain Cert already exist")
        else:
            with open(auth_chain_cert_source_path, 'wb') as auth_chain_cert_source_file:
                auth_chain_cert_source_file.write(auth_chain_cert_source_decode)
        if os.path.exists(auth_public_cert_source_path):
            print_to_stdout("Public Cert already exist")
        else:
            with open(auth_public_cert_source_path, 'wb') as auth_public_cert_source_file:
                auth_public_cert_source_file.write(auth_public_cert_source_decode)
        if os.path.exists(auth_private_key_source_path):
            print_to_stdout("Private Key already exist")
        else:
            with open(auth_private_key_source_path, 'wb') as auth_private_key_source_file:
                auth_private_key_source_file.write(auth_private_key_source_decode)

        certs = ({
           "client_cert_path": auth_public_cert_source_path,
           "client_key_path": auth_private_key_source_path,
           "server_cert": auth_chain_cert_source_path,
        })
        return certs  ## Return as dictionary so it can be pass

    except Exception as e:
        print_to_stdout(e)

 ## Function will dynamically populate the sub-folder of the vault instance by passing the root the path and the dic
def list_dir(path, client, dict):
    try:
        items = client.list(path)
        if not path.endswith("/"):
            path = path + "/"
        for item in items["data"]["keys"]:
            if item.endswith("/"):
                #print("This is a folder")
                list_dir(path + item, client, dict)
            else:
                #print("This is a secret")
                dict[path + item] = (client.read(path + item ))
    except Exception as e:
        print(e)

def authenticate_vault():
    get_certs = generate_certs()
    client_cert_path = get_certs["client_cert_path"]
    client_key_path = get_certs["client_key_path"]
    server_cert = get_certs["server_cert"]
    client = hvac.Client(url=vault_url_source, cert=(client_cert_path, client_key_path), verify=server_cert)
    client_verification = client.auth_tls()
    try:
        client_authentication = client.is_authenticated()
        if client_authentication == True:
            secret_list_result = {}
            client_verification = client.auth_tls()  # Authenticating to vault server
            response = client.list(vault_root_path) ## Reading from the vault
            secret_list = list_dir(vault_root_path, client, secret_list_result)
            print(secret_list_result)
        else:
            print_to_stdout("Couldn't authenticate to Vault..")
    except Exception as e:
        print_to_stdout(e)

def main():
    authenticate_vault()


if __name__ == '__main__':
    main()

**Comment by ewjoachim** [comment]
I'm not sure I understand what I'm supposed to do with this.

BTW, it looks like you can replace your `print_to_stdout` function with the `print` function from the Python standard library.

**Comment by johnyalejandro001** [comment]
The reason why I have in used is because majority of the script that I write are ran from TC in a docker container that is the only way I'm able to write stand-out to the screen log..

**Comment by ewjoachim** [comment]
Ok, seen with you directly :) The snippet above will not be useful for this issue, but I'm going to leave the issue open because I still believe set-all would be a nice feature to have in vault-cli.
