### ISSUE TITLE
Feature request: delete-all command

### ISSUE THREAD

**Issue by pilou-** [peopledoc/vault-cli#21]
Same as `get-all` but for recursive deletion:
`vault -U https://myvault.test:8200 -b myapp -w delete-all db/`

**Comment by ewjoachim** [comment]
Ok, but you better be seriously sure about what you're about to delete... Implement a molly-guard-like check ?

**Comment by pilou-** [comment]
This feature would be useful when testing the service.

@yannlachiver do not Vault policies prevent deletion (test instances excepted) ?
