### ISSUE TITLE
The name "vault" might be ambiguous

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/vault-cli#89]
Honestly, I'm not sure about this issue raised by @mgu (I'm naming names here :D), because "this ship has sailed". I'm -1 to removing the name `vault` by default but I'm absolutely not opposed to having another name in use too, and maybe ok having a mechanism to disable the creation of the `vault` entrypoint, but only if it's very explicit.

Id go so far as to say this: _someone_ could always register another package on PyPI which would either repackage the same code and change the entrypoint or depend on vault-cli and neutralize the entrypoint. I'm not saying it would be a good idea, though, but I can't keep them from doing this.

In this issue, we can discuss this matter. If everyone else is convinced that vault is a bad name compared to `<whatever>`, then it's easy to keep both names for 6 months with a deprecation warning, so I'll be following along.

**Comment by ewjoachim** [comment]
What about `vault-cli` ? We could have both name work (for an unlimited time).

**Comment by mgu** [comment]
I agree `vault` is ambiguous. `vault-cli` seems fine :)
