### ISSUE TITLE
base-path difference when using trailing slash or not

### ISSUE THREAD

**Issue by jacquesrott** [peopledoc/vault-cli#9]
When configuring your `vault.yml`, using a trailing or not will have different results.

```console
$ vault --base-path=base/ get test
foo
```

While

```console
$ vault --base-path=base get test
vault_cli.vault_python_api.VaultAPIException: status=403 error="permission denied"
```

**Comment by pilou-** [comment]
Was fixed by https://github.com/peopledoc/vault-cli/commit/24a30065ae37e3ca26b3ab3c96f015e9549e8004#diff-1813920f98649e73b8cb22442150cf6cR41.
